### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Appoxo** [TRaSH-/Guides#1353]
**Which Guide**
[Please add which Guide you found a Bug/Error with.](https://www.beisammen.de/index.php?thread/103397-unterschied-dts-hd-master-audio-zu-dts-hd-high-resolution/&postID=1115247#post1115247)

**Describe the Error in the Guide**
No description for the codec

**Expected behavior**
Suggested description:
"Basically DTS-HD MA but lossy"

**Screenshots**

**Additional context**
Based on those forum entries: 
https://www.beisammen.de/index.php?thread/103397-unterschied-dts-hd-master-audio-zu-dts-hd-high-resolution/&postID=1115247#post1115247
and
https://www.avsforum.com/threads/question-about-dts-hi-res-vs-dts-master.1327340/#post-20273990

**Comment by TRaSH-** [comment]
So what's the bug ?
https://en.wikipedia.org/wiki/DTS-HD_Master_Audio

DTS-HD Master Audio (DTS-HD MA; known as DTS++ before 2004[[1]](https://en.wikipedia.org/wiki/DTS-HD_Master_Audio#cite_note-:0-1)) is a [multi-channel](https://en.wikipedia.org/wiki/Surround_sound), [lossless](https://en.wikipedia.org/wiki/Lossless_data_compression) audio [codec](https://en.wikipedia.org/wiki/Codec) developed by [DTS](https://en.wikipedia.org/wiki/DTS_(sound_system)) as an extension of the [lossy](https://en.wikipedia.org/wiki/Lossy_compression) [DTS Coherent Acoustics](https://en.wikipedia.org/wiki/DTS_(sound_system)#DTS_Digital_Surround) codec (DTS CA; usually itself referred to as just DTS). Rather than being an entirely new coding mechanism, DTS-HD MA encodes an audio master in lossy DTS first, then stores a concurrent stream of supplementary data representing whatever the DTS encoder discarded. This gives DTS-HD MA a lossy "core" able to be played back by devices that cannot decode the more complex lossless audio. DTS-HD MA's primary application is audio storage and playback for [Blu-ray Disc](https://en.wikipedia.org/wiki/Blu-ray_Disc) media; it competes in this respect with [Dolby TrueHD](https://en.wikipedia.org/wiki/Dolby_TrueHD), another lossless surround format. DTS-HD MA has enjoyed the greater share of this market since 2010,[[2]](https://en.wikipedia.org/wiki/DTS-HD_Master_Audio#cite_note-2) with the notable exception of the TrueHD-encoded [Dolby Atmos](https://en.wikipedia.org/wiki/Dolby_Atmos) spatial surround format, which is more popular than DTS's competing [DTS:X](https://en.wikipedia.org/wiki/DTS_(sound_system)#DTS:X) (encoded with DTS-HD MA).

And this info is provided in the guide

**Comment by Appoxo** [comment]
I just wanted to fill the "Description placeholder" if it is explained elsewhere I would suggest just linking it.
If unnecessary/redundant just close the issue

**Comment by TRaSH-** [comment]
hmm, took a while till i could figure out what you mean
i thought you mean the following [DTS-HD MA](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#dts-hd-ma)
but you actually mean [DTS-HD HR](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#dts-hd-hra)

if you want to you can create PR for [DTS-HD HR](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#dts-hd-hra)
or create a description what should be added, including a official source explaining it.
some random foreign forum won't do it, so you will need to find some official sources for this info

**Comment by Appoxo** [comment]
Gotcha. I will look into it!
Thanks for your time  
And sorry for being confusing :)
