### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Getn67** [TRaSH-/Guides#282]
** Which Guide **
Bazarr/Basic-Guide

**Describe the Error in the Guide**
Redundant Language on step four.

"Meanly used when you use a reverse proxy." can be removed outright.

**Additional context**
The blurb stands on its own without the last sentence.

**Comment by Getn67** [comment]
The issue appears in the Radarr section as well.

**Comment by TRaSH-** [comment]
It's added on purpose because on discord we get in every arr server often the same question when they should make use of it.
Or even users that don't use reverse proxy and just add the base url and then wonder why it doesn't work.
It's the same with the bind address, somehow people always tent to change it without knowing what it does.

**Comment by Getn67** [comment]
I've cloned the Repo for myself... Lemme see if I can make it concise without being redundant.

**Comment by TRaSH-** [comment]
Sure np,
Just make sure it's understandable for someone not that tech savvy.
