### ISSUE TITLE
[INFO] Docker Compose  v2 

### ISSUE THREAD

**Issue by doob187** [TRaSH-/Guides#355]
Info 

https://docs.docker.com/compose/cli-command/

Compose V2 and the new docker compose command🔗
Important

The new Compose V2, which supports the
compose command as part of the Docker CLI, is now available.

Compose V2 integrates compose functions into the Docker platform, continuing to support most of the previous docker-compose features and flags. You can test the Compose V2 by simply replacing the dash (-) with a space, and by running docker compose, instead of docker-compose.

**Comment by TRaSH-** [comment]
Thnx,
I'll keep it mind for for upcoming updates, and when it starts to get more common for different OS's
@nemchik I presume you also would be interested in this.

**Comment by nemchik** [comment]
I've got eyes on it. A future version of docker will come with compose v2 built in.

**Comment by TRaSH-** [comment]
> I've got eyes on it. A future version of docker will come with compose v2 built in.

Let me know, so i know when i should update.
I'll keep this pinned so we don't forget ;)

**Comment by nemchik** [comment]
it looks like it's not 100% compatible with v1, but by the sounds of it we are better off adjusting things we have that use compose to be compatible with v2. they should be mostly backwards compatible afterwards. main thing i noticed right off the bat was v2 is picky about the values inside environment variables. it doesn't like what i have for one of my watchtower variable values. i'll investigate and work on it.

also, i don't love that they are recommending to install v2 in the user home directory. you can also install it globally, and you could end up with multiple different versions installed, which could lead to inconsistencies. i'd like to see them just bake it into the docker command line rather than asking users to install it separately, but i don't know how soon that'll happen. alternatively they could do something like `docker plugin install compose` but they have already said there shouldn't be a need for that once it's built into the docker cli, so they aren't going to put efforts into the plugin install method.

**Comment by nemchik** [comment]
Not stale, but no updates.
