### ISSUE TITLE
[REQUEST] A basic terminology, scene, group, etc guide

### ISSUE THREAD

**Issue by rcdailey** [TRaSH-/Guides#71]
I'm personally unfamiliar with scenes/groups. First of all, there's a lot of terminology so it would be great to see all of that outlined.

I think the most important benefit of this guide would be explaining how you came to understand what you want out of your releases/downloads, how do you educate yourself on which groups are good or bad for releases on usenet/torrent? After going through your guide on recommended release profiles and custom formats, it became very apparent to me that there's a LOT to sift though. You have a lot of low quality groups you exclude. There are preferences for some groups over others, for lots of reasons: Quality, size of releases, timing of releases, how they name their files, etc. And finally, I'm sure this changes a lot. Groups may come and go. How do you keep up to date with this and understand which groups you like or don't like?

This is a "teach a man to fish" moment: Your guides are excellent for getting someone started, but I think long term it makes sense to be equipped with the tools and knowledge necessary to make my own updates and personal touches to the framework you have started.

**Comment by TRaSH-** [comment]
Well most of your questions I got actually described in the guides it self why I prefer P2P groups over over scene releases.
Why certain groups are in the low quality profile.
And where I get the info from without telling where I get my "Linux ISO's" from.
If you got access to those sources then you would know.
Because things change it's actually best to subscribe to my GitHub and join my discord server/channel where I announce any updates and why.
And try to give any needed support for any questions related to the guides.

**Comment by rcdailey** [comment]
That's certainly an option, I was thinking a guide would be more respectful (and a better use) for your time. But I won't argue against you helping personally, it's certainly appreciated!

Yes I did see some things discussed in fragments but it wasn't all centralized, and even after reading it I'm personally still far from understanding the topics I originally mentioned.

You are welcome to not like my idea and close this one. My feelings won't be hurt. I really just wanted to see how you felt about it. Not asking for trade secrets or anything like that, just a way for a person to become more independently knowledgeable. Either way, thanks for all you do!

**Comment by TRaSH-** [comment]
I always want to try to get to a agreement  if possible,
the main reason why i add the info with the parts where it's used is so users remember.
if i add the info in a main guide/description users won't have read it perhaps or forgot it already.

And the info I gather from different sources isn't something public except the info gathered from Discord/Reddit.
but this means you need to be present all the time and read back the info from the channels

If you got access to the sources where i get the info from you probably won't really need the guides to decide what you actually want/need.

That's why i put the updates i do on my discord channel and people can ask questions and give feedback what might need to be changed

Examples where the info is described with the parts where it's needed and used.

![image](https://user-images.githubusercontent.com/6155095/103108227-22c62c80-4646-11eb-9cf3-b69b03d5fe9a.png)

![image](https://user-images.githubusercontent.com/6155095/103108237-3f626480-4646-11eb-9f7d-8db4621f6079.png)

![image](https://user-images.githubusercontent.com/6155095/103108243-51440780-4646-11eb-9ad2-f13f0587bc04.png)
