### ISSUE TITLE
BR-Disk Custom Format in Radarr tagging mkv release incorrectly

### ISSUE THREAD

**Issue by kevindd992002** [TRaSH-/Guides#75]
I've started using your CF guide for Radarr and I'm having issues with the BR-Disk CF. It's tagging mkv releases as BR-Disk which obviously we do not want. Why? For example:

![image](https://user-images.githubusercontent.com/3907957/103305187-6bfeed80-4a45-11eb-9284-7d5baa991ee6.png)

That release is an mkv file but based on the conditions in your BR-Disk CF, the strings in the release title is causing it to be tagged as a BR-Disk. Is this a bug on that CF?

**Comment by TRaSH-** [comment]
Only thing i can think off
![image](https://user-images.githubusercontent.com/6155095/103311425-a30bd980-4a1a-11eb-9304-3866bb61783b.png)

Not much i can do about it to fix it.
You got 2 options.
Get another release, theirs a remux floating around that i would suggest.
Force download the movie.

**Comment by kevindd992002** [comment]
I thought that note was only applicable for releases that were downloaded and renamed already, that's
why I didn't really focused on it?

The screenshot I posted was just an example as I was testing how these CF's all work. After I'm happy with the results, I will update my whole library.

I still don't understand though, why is the BR-Disk CF still needed if the BR-Disk quality is already unchecked? I haven't had an instance where a BR-Disk was downloaded accidentally without the CF and with the BR-Disk quality unchecked.

**Comment by TRaSH-** [comment]
You don't need it if you don't think you need it.
I just noticed often that a bunch of BR-DISK where downloaded but not recognized as BR-DISK and I ended up with ISO's.
To my knowledge Radarr only checks for the word disc or something similar.
And allot of BR-DISK don't have the word disc in it.
And are named differently and that's where this custom format steps in.
Since I use this custom format I never gotten a single BR-DISK anymore.
And the few bad named releases like you showed me that get wrongly marked as BR-DISK I could care less about.
And I rather get correctly named releases.
If it's a encode it's wrongly named anyway being it should have x265 in it, if it's a remux it should have the word remux in it.

**Comment by kevindd992002** [comment]
I see. In my specific example, isn't HEVC the same as x265? Or is x265 the standard that should be in the filenames?

**Comment by TRaSH-** [comment]
No it isn't

x265 is a free software library and application for encoding video streams into the H.265/MPEG-H HEVC compression format, 

So x265 is used for encoding.

**Comment by kevindd992002** [comment]
I see. It's just they often come together. So with x265 and HEVC in the filename, this will not be incorrectly tagged as BR-Disk, yes?
