### ISSUE TITLE
[Sonarr] Golden Rule Tweak

### ISSUE THREAD

**Issue by merqwury** [TRaSH-/Guides#842]
**Which Guide**
Sonarr guide

**Describe the Error in the Guide**
I've noticed some groups have released x265 releases from 1080p with HDR/DV, and x264 without it. In this case, in my opinion, the x265 is preferably to the x264 version, however, using the golden rule (sonarr) gives it a lower score. 

For example:

```
The.Cuphead.Show.S01.1080p.NF.WEB-DL.DDP5.1.H.264-TEPES <--- No HDR/DV
The.Cuphead.Show.S01.DV.1080p.NF.WEB-DL.DDP5.1.H.265-HDCTV <-- DV
The.Cuphead.Show.S01.HDR.1080p.NF.WEB-DL.DDP5.1.H.265-HDCTV <-- HDR
```

Using the Golden Rule, as it stands today, it would score the first release highest.

**Expected behavior**
I would expect the x265 versions (with DV/HDR) to score higher than x264 versions.

**Comment by TRaSH-** [comment]
I used to have a except rule but got many complains that the regex didn't do what it should do so I reverted it.

I won't be putting much time in feature requests for Sonarr v3 and only will do needed updates.
All feature requests will be done for Sonarr v4 because it's more flexible with the introduction of custom formats like what Radarr is using.
And for Sonarr v4 it already exist.
