### ISSUE TITLE
[REQUEST] downloaders - transmission

### ISSUE THREAD

**Issue by thezoggy** [TRaSH-/Guides#911]
**For which application would like to see this Guide ?**
Radarr / Sonarr / Bazarr / etc

**Describe what you would like to see in the Tutorial/Guide**
Some people still use transmission? might as well add notes about what version is supported/how to set it up for *arr

**Comment by TRaSH-** [comment]
The reason why I didn't add transmission is because the support team doesn't recommend transmission for automation, mainly that transmission doesn't have categories, and yes there is a work around with folders, but still not optimal.
Till now the support team recommend
- Qbt
- deluge
- rtorrent

**Comment by thezoggy** [comment]
ack, i only bring this up because in sonarr discord there seems to be a lot of transmission users lately and we tell them to go to trash guides and was shocked to not have it listed

**Comment by TRaSH-** [comment]
I'm more shocked that any one tells them to use transmissions in the first place (especially a Pre-release ;) )
I'm not in Sonarr discord, and only keep track on the Servarr apps discord, and i think i only seen one asking about transmission, where the support team actually suggested to switch to another client, that actually support labels/categories.

Perhaps if transmission starts supporting labels/categories and is out of Pre-release i might add some info to the guide for it.

**Comment by thezoggy** [comment]
disclaimer: i dont use torrents, i just have been asking related stuff due to *arr support channels and such. i'm bias for usenet :)

Now, I know someone that is using transmission 2.94 from 2018! and in his sonarr transmission settings I see there is a category spot and seems to work fine..  which has been there for 7+ years now..  looks like sonarr/radarr just require transmission 2.4+

**Comment by TRaSH-** [comment]
i use both, and i try to keep the guide up to date with the Starr apps support channel and suggestions, and i never seen someone from the support team suggest transmissions if someone aks which torrent client to use.
And when some ask a question about transmission they always been asked why they don't use a better torrent client that works better with automation.
Yes i do know the Starr apps support transmission but they also support other even worse crappy torrent clients that the support team never recommend and when someone ask about it they actually get minimal to no help for.
ex. utorrent, downloadstation etc etc

But I will keep a eye on it and keep in touch with the Starr support team (mainly Radarr being i'm only in toch with them) if it's really needed to provide a basic setup guide for transmission, as long as the support team doesn't name them in 1 line (Qbt => Deluge => rTorrent) as suggested torrent clients, i don't think it should be added to prevent extra not wanted support questions of a app/client that hardly any one uses.

Thnx for your feedback, and all the help with SABnzbd, a app i do recommend everyone as usenet client. (even that i don't use it myself because of a few personal minor annoyance that are getting less and less)

**Comment by brandonb927** [comment]
I don't mean to revive this multi-year-old issue, but I just finished writing a script to automate starting-stopping of torrents in Transmission 4.0+ using the `transmission-rpc` python3 package if anyone is interested. I can start a new issue or a discussion if that is also preferred.

**Comment by TRaSH-** [comment]
> I don't mean to revive this multi-year-old issue, but I just finished writing a script to automate starting-stopping of torrents in Transmission 4.0+ using the `transmission-rpc` python3 package if anyone is interested. I can start a new issue or a discussion if that is also preferred.

We don't have a transmission guide so i wouldn't know where to place this,  and this would act the same as what we have for Qbt like the Qbt mover script for unRaid?

**Comment by brandonb927** [comment]
> > I don't mean to revive this multi-year-old issue, but I just finished writing a script to automate starting-stopping of torrents in Transmission 4.0+ using the `transmission-rpc` python3 package if anyone is interested. I can start a new issue or a discussion if that is also preferred.
> 
> We don't have a transmission guide so i wouldn't know where to place this, and this would act the same as what we have for Qbt like the Qbt mover script for unRaid?

Fair enough! Yes it would function almost exactly the same. I'm just wrapping up some finishing touches on it soon and I'll throw it up in a GitHub Gist then link it here.

**Comment by brandonb927** [comment]
Here is a version of the qbit_manage mover.py for Transmission 4.0+ https://gist.github.com/brandonb927/652ecf1bb23dc7a94e140c95a9e7b5e1

It allows for URL or IP-based address for the `--host` arg as well.
