### ISSUE TITLE
[REQUEST] torrent feature matrix

### ISSUE THREAD

**Issue by thezoggy** [TRaSH-/Guides#912]
**For which application would like to see this Guide ?**
Radarr / Sonarr / Bazarr / etc

**Describe what you would like to see in the Tutorial/Guide**
Have a landing page that lists the various popular torrent clients and if they have features/support for things that matter to the *arr universe.

- can you blacklisting extensions (.scr/.iso spam)
- segment downloads by app (labels/subfolder/whatever)
- remove torrent by seed/time -- https://wiki.servarr.com/sonarr/settings#torrent-client-remove-download-compatibility
- handled rar's natively (* use unpackerr)
- which is better for seedbox (thousands of torrents) - cli/api support

**Comment by TRaSH-** [comment]
I already had plans to cover a few of your suggestions, except the seedbox stuff, mainly because I don't have or used a seedbox and don't want the support questions you will get with it including cloud storage.

Landing page I already have for the downloaders, so I could take a look at it to add certain features.
But this will be low priority.
Thinking about it the 3 recommended torrent clients all support label/category and for those lame trackers that still allow packed torrents the support team still recommend unpackerr.

I'll take a look at it what's possible without adding loads of time to maintain it 
Thx
